#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file creates all WANdisco Fusion services needed to
# stand up an HDI zone.
#
# Services running in each zone
#     Zone
#         Fusion UI Server HDI  (fusion-ui-server-s3)
#         Fusion IHC Server     (fusion-ihc-server-s3)
#         Fusion Server         (fusion-server-s3)
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - logging-s3:/debug/s3
    networks:
      - fusion

  # Fusion UI Server
  fusion-ui-server-s3:
    image: wandisco/fusion-ui-server-hcfs-asf-3.1.0:2.15.5.1-3860
    depends_on:
      - fusion-server-s3
    networks:
      - fusion
    ports:
      - 8583:8583
      - 8943:8943
    restart: unless-stopped
    env_file:
      - "zone_b.env"
    volumes:
      - logging-s3:/var/log/fusion
      - fusion-s3-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-s3-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-s3-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      - fusion-s3-etc-wandisco:/etc/wandisco
      - fusion-s3-hdfs-home-aws:/home/hdfs/.aws

  # Fusion IHC Server
  fusion-ihc-server-s3:
    image: wandisco/fusion-ihc-server-hcfs-asf-3.1.0:2.15.5.1-3860
    depends_on:
      - fusion-server-s3
    networks:
      - fusion
    # Note: standard ports have been incremented by 500 to remove conflicts between Zone 1 and Zone 2
    ports:
      - 7500:7500
      - 7501:7501
      - 9502:9502
    restart: unless-stopped
    env_file:
      - "zone_b.env"
    volumes:
      - logging-s3:/var/log/fusion
      - fusion-s3-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-s3-etc-wandisco:/etc/wandisco
      - fusion-s3-hdfs-home-aws:/home/hdfs/.aws
      - fusion-s3-restart:/var/run/wandisco/ihc

  # Fusion Server
  fusion-server-s3:
    image: wandisco/fusion-server-hcfs-asf-3.1.0:2.15.5.1-3860
    networks:
      - fusion
    # Note: standard ports have been incremented by 500 to remove conflicts between Zone 1 and Zone 2
    ports:
      - 8524:8524
      - 8523:8523
      - 8582:8582
      - 8584:8584
      - 6944:6944
    restart: unless-stopped
    environment:
      - DB_ACTION=
    env_file:
      - "zone_b.env"
    volumes:
      - logging-s3:/var/log/fusion
      - fusion-s3-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-s3-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-s3-hdfs-home-aws:/home/hdfs/.aws
      - fusion-s3-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      - fusion-s3-etc-wandisco:/etc/wandisco
      - fusion-s3-restart:/var/run/wandisco/ihc

networks:
  # One Docker network is shared between both zones
  fusion: {}

volumes:
  # The named logging volumes for all components
  logging-s3:

  # Checkpoint volume (confirm if this is needed to persist across container restarts)
  fusion-s3-opt-wandisco-fusion-server-checkpoint:

  # dcone volume to persist database changes across restarts
  fusion-s3-opt-wandisco-fusion-server-dcone:

  # volumes for persisting config
  fusion-s3-etc-wandisco:
  fusion-s3-hdfs-home-aws:
  fusion-s3-opt-wandisco-fusion-ui-server-properties:
